### ISSUE TITLE
Improve download performance (Windows Powershell installer)

### ISSUE THREAD

**Issue by fdcastel** [openobserve/agents#8]
Using `Invoke-WebRequest` for downloading large payloads in Powershell is [notoriously inefficient](https://stackoverflow.com/a/43477248/33244).

To significantly enhance download speed, please add

```powershell
$ProgressPreference = 'SilentlyContinue'
```

before the `Invoke-WebRequest` call.

**Comment by prabhatsharma** [comment]
https://github.com/openobserve/agents/commit/2cde757c0e14fd8aee04c9959c999107d181be98
